project: brugada
approach: regular

data:
  num_shots: 0 # 3, 5, 10
  datafile_path: ./data/${project}
  label_replacements:
  label_predictions:
    "Normal": 0
    "Brugada": 1
  save_path: ./results/${project}/${approach}/${data.num_shots}

model:
  model_name: gpt-4o # gpt-4o, med-gemma-4b-it, PULSE

user_args:
  system_prompt_path: ./prompts/${project}/system_prompt.txt
  user_query_path: ./prompts/${project}/user_prompt_${name}.txt
  verbose: True
  debug: False
  batched: False